backend/config/routes.rb
Rails.application.routes.draw do
  # post 'user_token' => 'user_token#create'
  devise_for :users
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registrations: 'registrations' }
      resources :comment_likes
      resources :likes
      resources :posts
      resources :users
      resources :comments
      resources :sessions
      post 'auth/register' , to: 'users#register'
      post 'auth/login' , to: 'users#login'
      get 'test' , to: 'users#test'
      put 'users', to: 'users#update'
      post 'password/forgot', to: 'users#forgot'
      post 'password/reset', to: 'password#reset'
      post 'search',to:'posts#search'
      post 'user/search',to:'users#search'
      devise_scope :user do
        # post "register", :to => 'registrations#create'
        # post "login", :to => 'sessions#create'
        # delete "logout", :to => 'sessions#destroy'
        # put "users/:id", to: "registrations#update"
      end
      namespace :admin do
        delete 'users/:id', to: 'users#destroy'
        put 'posts/:id', to: 'posts#update'
        delete 'posts/:id', to: 'posts#destroy'
        delete 'comments/:id', to: 'comments#destroy'
        get 'posts',to:'posts#getpost'
       
      end
    end
  end
end

backend/app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :comments, optional: true
end

backend/app/controllers/api/v1/comment_likes_controller.rb
class Api::V1::CommentLikesController < ApplicationController
  before_action :set_comment_like, only: %i[ show edit update destroy ]

  # GET /comment_likes or /comment_likes.json
  def index
    @comment_likes = CommentLike.all

    render json: @comment_likes
  end

  # GET /comment_likes/1 or /comment_likes/1.json
  def show
    render json: comment_like
  end

  # GET /comment_likes/new
  def new
    @comment_like = CommentLike.new
  end

  # GET /comment_likes/1/edit
  def edit
  end

  # POST /comment_likes or /comment_likes.json
  def create
    @comment_like = CommentLike.new(comment_like_params)

    if @comment_like.save
      render json: @comment_like, status: :created
    else
      render json: @comment_like, status: :unprocessable_entity
    end

    # respond_to do |format|
    #   if @comment_like.save
    #     format.html { redirect_to comment_like_url(@comment_like), notice: "Comment like was successfully created." }
    #     format.json { render :show, status: :created, location: @comment_like }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @comment_like.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /comment_likes/1 or /comment_likes/1.json
  def update
    if @comment_like.update(comment_like_params)
      render json: @comment_like
    else
      render json: @comment_like.errors, status: :unprocessable_entity
    end

    # respond_to do |format|
    #   if @comment_like.update(comment_like_params)
    #     format.html { redirect_to comment_like_url(@comment_like), notice: "Comment like was successfully updated." }
    #     format.json { render :show, status: :ok, location: @comment_like }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @comment_like.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /comment_likes/1 or /comment_likes/1.json
  def destroy
    @comment_like.destroy

    # respond_to do |format|
    #   format.html { redirect_to comment_likes_url, notice: "Comment like was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment_like
      @comment_like = CommentLike.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_like_params
      params.require(:comment_like).permit(:count, :comment_id)
    end
end

backend/app/helpers/comment_likes_helper.rb
module CommentLikesHelper
end

backend/app/views/comment_likes/_form.html.erb
<%= form_with(model: comment_like, local: true) do |form| %>
  <% if comment_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment_like.errors.count, "error") %> prohibited this comment_like from being saved:</h2>

      <ul>
        <% comment_like.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :comment_id %>
    <%= form.text_field :comment_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/comment_likes/edit.html.erb
<h1>Editing Comment Like</h1>

<%= render 'form', comment_like: @comment_like %>

<%= link_to 'Show', @comment_like %> |
<%= link_to 'Back', comment_likes_path %>

backend/app/views/comment_likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comment Likes</h1>

<table>
  <thead>
    <tr>
      <th>Count</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comment_likes.each do |comment_like| %>
      <tr>
        <td><%= comment_like.count %></td>
        <td><%= comment_like.comment_id %></td>
        <td><%= link_to 'Show', comment_like %></td>
        <td><%= link_to 'Edit', edit_comment_like_path(comment_like) %></td>
        <td><%= link_to 'Destroy', comment_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment Like', new_comment_like_path %>

backend/app/views/comment_likes/new.html.erb
<h1>New Comment Like</h1>

<%= render 'form', comment_like: @comment_like %>

<%= link_to 'Back', comment_likes_path %>

backend/app/views/comment_likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Count:</strong>
  <%= @comment_like.count %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment_like.comment_id %>
</p>

<%= link_to 'Edit', edit_comment_like_path(@comment_like) %> |
<%= link_to 'Back', comment_likes_path %>