backend/config/routes.rb
Rails.application.routes.draw do
  # post 'user_token' => 'user_token#create'
  devise_for :users
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registrations: 'registrations' }
      resources :comment_likes
      resources :likes
      resources :posts
      resources :users
      resources :comments
      resources :sessions
      post 'auth/register' , to: 'users#register'
      post 'auth/login' , to: 'users#login'
      get 'test' , to: 'users#test'
      put 'users', to: 'users#update'
      post 'password/forgot', to: 'users#forgot'
      post 'password/reset', to: 'password#reset'
      post 'search',to:'posts#search'
      post 'user/search',to:'users#search'
      devise_scope :user do
        # post "register", :to => 'registrations#create'
        # post "login", :to => 'sessions#create'
        # delete "logout", :to => 'sessions#destroy'
        # put "users/:id", to: "registrations#update"
      end
      namespace :admin do
        delete 'users/:id', to: 'users#destroy'
        put 'posts/:id', to: 'posts#update'
        delete 'posts/:id', to: 'posts#destroy'
        delete 'comments/:id', to: 'comments#destroy'
        get 'posts',to:'posts#getpost'
       
      end
    end
  end
end

backend/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :posts, optional: true
  belongs_to :users, optional: true
end

backend/app/controllers/api/v1/likes_controller.rb
class Api::V1::LikesController < ApplicationController
  before_action :set_like, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [ :update, :destroy]
  # GET /likes or /likes.json
  def index
    @likes = Like.all

    render json: @likes
  end

  # GET /likes/1 or /likes/1.json
  def show
    # render json: @like
    if correct_user
      @likes = Like.all
      render json: { statusCode: 200 ,  message: 'Delete post successfully'}, status: :ok
    else
      render json: {message: 'Incorrect user'}
    end
  end

  # GET /likes/new
  # def new
  #   @like = Like.new
  # end

  # GET /likes/1/edit
  # def edit
  # end

  # POST /likes or /likes.json
  def create
    @like = Like.new(like_params)

    if @like.save
      render json: Like.all, status: :created
    else
      render json: @like.errors, status: :unprocessable_entity
    end
    # respond_to do |format|
    #   if @like.save
    #     format.html { redirect_to like_url(@like), notice: "Like was successfully created." }
    #     format.json { render :show, status: :created, location: @like }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @like.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /likes/1 or /likes/1.json
  def update
    if @like.update(like_params)
      render json: @like
    else
      render json: @like.errors, status: :unprocessable_entity
    end

    # respond_to do |format|
    #   if @like.update(like_params)
    #     format.html { redirect_to like_url(@like), notice: "Like was successfully updated." }
    #     format.json { render :show, status: :ok, location: @like }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @like.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /likes/1 or /likes/1.json
  def destroy
    if correct_user
      @like.destroy
      render json: { statusCode: 200 , data: Like.all , message: 'Delete Like Of Post  successfully'}, status: :ok
    else
      render json: {message: 'Incorrect user'}
    end
  end
  def correct_user
    @like = current_user.likes.find_by(post_id: params[:id])
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def like_params
      params.require(:like).permit(:post_id, :user_id)
    end
end

backend/app/helpers/likes_helper.rb
module LikesHelper
end

backend/app/views/likes/_form.html.erb
<%= form_with(model: like, local: true) do |form| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

backend/app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.post_id %></td>
        <td><%= like.user_id %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

backend/app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

backend/app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @like.post_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @like.user_id %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>